mv AKUTAGAWA_RASHOMON_1.jpeg AUTOR_LIVRO_1.jpeg
mv AKUTAGAWA_RASHOMON_2.jpeg AUTOR_LIVRO_2.jpeg
mv AKUTAGAWA_RASHOMON_3.jpeg AUTOR_LIVRO_3.jpeg
mv AKUTAGAWA_RASHOMON_4.png AUTOR_LIVRO_4.png
mv AKUTAGAWA_RASHOMON.pdf AUTOR_LIVRO.pdf
mv AKUTAGAWA_RASHOMON_THUMB.pdf AUTOR_LIVRO_THUMB.pdf
rm NIETZSCHE_GREGOS_DETALHE.pdf
