pandoc NIETZSCHE_GREGOS.tex -o NIETZSCHE_GREGOS.md
pandoc HIPOCRATES.docx -o HIPOCRATES.md
pandoc JULIA_MEDEIROS.docx -o JULIA_MEDEIROS.md
pandoc NIETZSCHE_HISTORIA.docx -o NIETZSCHE_HISTORIA.md
pandoc ORIDES_HELIANTO.docx -o ORIDES_HELIANTO.md
pandoc ORIDES_TRANSPOSICAO.docx -o ORIDES_TRANSPOSICAO.md
pandoc VARIOS.docx -o VARIOS.md
pandoc XAMANISMOS.tex -o XAMANISMOS.md
